// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {service} from '../models';

export function ActionDeletePages(arg1:string,arg2:string,arg3:string):Promise<main.Result>;

export function ActionMergePDF(arg1:Array<string>,arg2:string):Promise<service.ProcessResult>;

export function ActionPdfToWord(arg1:string,arg2:string):Promise<service.ProcessResult>;

export function ActionWordToPdf(arg1:string,arg2:string):Promise<service.ProcessResult>;

export function DeletePages(arg1:string,arg2:Array<number>,arg3:string):Promise<string>;

export function GetPdfPagePreviews(arg1:string):Promise<Array<service.PdfPagePreview>>;

export function GetSavePath(arg1:string,arg2:string):Promise<string>;

export function OpenFileFolder(arg1:string):Promise<void>;

export function SelectMultipleFiles():Promise<Array<string>>;

export function SelectSingleFile(arg1:string,arg2:string):Promise<string>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;
