// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActionDeletePages(arg1, arg2, arg3) {
  return window['go']['main']['App']['ActionDeletePages'](arg1, arg2, arg3);
}

export function ActionMergePDF(arg1, arg2) {
  return window['go']['main']['App']['ActionMergePDF'](arg1, arg2);
}

export function ActionPdfToWord(arg1, arg2) {
  return window['go']['main']['App']['ActionPdfToWord'](arg1, arg2);
}

export function ActionWordToPdf(arg1, arg2) {
  return window['go']['main']['App']['ActionWordToPdf'](arg1, arg2);
}

export function DeletePages(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeletePages'](arg1, arg2, arg3);
}

export function GetPdfPagePreviews(arg1) {
  return window['go']['main']['App']['GetPdfPagePreviews'](arg1);
}

export function GetSavePath(arg1, arg2) {
  return window['go']['main']['App']['GetSavePath'](arg1, arg2);
}

export function OpenFileFolder(arg1) {
  return window['go']['main']['App']['OpenFileFolder'](arg1);
}

export function SelectMultipleFiles() {
  return window['go']['main']['App']['SelectMultipleFiles']();
}

export function SelectSingleFile(arg1, arg2) {
  return window['go']['main']['App']['SelectSingleFile'](arg1, arg2);
}

export function ShowNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2);
}
